import Header from '@/components/Header'
import ServerList from '@/components/ServerList'
import axios from 'axios'
import Head from 'next/head'
import { useEffect } from 'react'

export default function Home() {

  return (
    <>
      <Head>
        <title>PteroTunnel</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
        <ServerList />
      </main>
    </>
  )
}
